# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Picture_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pic_x', models.IntegerField(default=0)),
                ('pic_y', models.IntegerField(default=0)),
                ('pic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagging.Picture')),
            ],
        ),
    ]
